../tlul_pkg.sv 
../tlul_host_adapter.sv 
../tlul_xbar_3s.sv 
../tlul_adapter_mem.sv 
../tlul_adapter_peri.sv 
../uart_byte_tx.sv 
../uart_byte_rx.sv 
../tlul_uart_bridge.sv 
../../00_src/memory.sv 
../../00_src/SevenSegment.sv 
../../00_src/peripherals.sv 
../../00_src/pc.sv 
../../00_src/PCplus4.sv 
../../00_src/instr_mem.sv 
../../00_src/IF.sv 
../../00_src/IF_ID_reg.sv 
../../00_src/regfile.sv 
../../00_src/immgen.sv 
../../00_src/control_logic.sv 
../../00_src/ID.sv 
../../00_src/ID_EX_reg.sv 
../ID_EX_reg_tl.sv 
../../00_src/fa.sv 
../../00_src/cla_4bit.sv 
../../00_src/cla_32bit.sv 
../../00_src/alu.sv 
../../00_src/brc.sv 
../../00_src/mux2.sv 
../../00_src/mux3.sv 
../../00_src/mux4.sv 
../../00_src/mux4_fw.sv 
../../00_src/EX.sv 
../../00_src/EX_MEM_reg.sv 
../EX_MEM_reg_tl.sv 
../../00_src/hazard_detection.sv 
../hazard_detection_tl.sv 
../../00_src/forwarding_unit.sv 
../../00_src/branch_predictor.sv 
../MEM_tl.sv 
../../00_src/MEM.sv 
../../00_src/MEM_WB_reg.sv 
../MEM_WB_reg_tl.sv 
../../00_src/mux3_wb.sv 
../../00_src/WB.sv 
../pipelined_tl.sv 
../soc_top.sv 
